// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FilterType: typeof import('./src/components/filterType/index.vue')['default']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutList: typeof import('@nutui/nutui-taro')['List']
    PersonInfo: typeof import('./src/components/personInfo/index.vue')['default']
    PostItem: typeof import('./src/components/postItem/index.vue')['default']
  }
}
