// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FilterType: typeof import('./src/components/filterType/index.vue')['default']
    ListItem: typeof import('./src/components/listItem/index.vue')['default']
    NutActionSheet: typeof import('@nutui/nutui-taro')['ActionSheet']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutImagePreview: typeof import('@nutui/nutui-taro')['ImagePreview']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutList: typeof import('@nutui/nutui-taro')['List']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutTextarea: typeof import('@nutui/nutui-taro')['Textarea']
    NutUploader: typeof import('@nutui/nutui-taro')['Uploader']
    PostItem: typeof import('./src/components/postItem/index.vue')['default']
    UserInfo: typeof import('./src/components/userInfo/index.vue')['default']
  }
}
